# This file was generated by GoReleaser. DO NOT EDIT.
cask "khbb" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "b345fd743b01313fabe22970bcb59f55f5feefd35a1f06c0d02d3ca9d7883c08"
      url "https://github.com/khipu/khbb/releases/download/v#{version}/khbb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc2012314812b64e26433da0bdc85dc65249fde928180670ca3f99ec23e35377"
      url "https://github.com/khipu/khbb/releases/download/v#{version}/khbb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1ec81687cf4d2079616ae52ed398d37093c6b2d5e28cb5a285c36943a5f933a4"
      url "https://github.com/khipu/khbb/releases/download/v#{version}/khbb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "98943cbd33bde4d8436aed9ecb5d39e3640ead15b4cfd77637ca4bcdb5440fea"
      url "https://github.com/khipu/khbb/releases/download/v#{version}/khbb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "khbb"
  desc "Bitbucket Cloud CLI for pull requests and pipelines"
  homepage "https://github.com/khipu/khbb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "khbb"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/khbb"]
    end
  end

  generate_completions_from_executable "khbb",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
