# This file was generated by GoReleaser. DO NOT EDIT.
cask "khbb" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "a8e1fd859beb1a78c286922c8dbd92836feeb6ac57cdb1e08a43db1806bdab64"
      url "https://github.com/khipu/khbb/releases/download/v#{version}/khbb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2044fad3d3056e4344c3c4014df444166995c207d15174e91d747014797f7c7a"
      url "https://github.com/khipu/khbb/releases/download/v#{version}/khbb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "69420cea56da692e71830f7d3fcbf12f6884f9bfb5ac11ab1477e95788a89a52"
      url "https://github.com/khipu/khbb/releases/download/v#{version}/khbb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fdde94d4740f26972375e25f905b5e89794cd808326735ff92d350f49f5fff7f"
      url "https://github.com/khipu/khbb/releases/download/v#{version}/khbb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "khbb"
  desc "Bitbucket Cloud CLI for pull requests and pipelines"
  homepage "https://github.com/khipu/khbb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "khbb"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/khbb"]
    end
  end

  generate_completions_from_executable "khbb",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
