# This file was generated by GoReleaser. DO NOT EDIT.
cask "khbb" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "2577b74b9f0e660c0abcd15289c4f9ed3f1d944da2d0c4a17280c6ff912732e7"
      url "https://github.com/khipu/khbb/releases/download/v#{version}/khbb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b0fa5febeadab4adb97c6157ae952edb98fd63dade1666f56211be4e87243776"
      url "https://github.com/khipu/khbb/releases/download/v#{version}/khbb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e6be93d1b4de2978698d10c272680e708796d6f7c09ae8e40312795674f96ddb"
      url "https://github.com/khipu/khbb/releases/download/v#{version}/khbb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eae228623edecddbdfaf55639bb40499df3cb7d45564ed0d3ea47b23e6d04afb"
      url "https://github.com/khipu/khbb/releases/download/v#{version}/khbb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "khbb"
  desc "Bitbucket Cloud CLI for pull requests and pipelines"
  homepage "https://github.com/khipu/khbb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "khbb"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/khbb"]
    end
  end

  generate_completions_from_executable "khbb",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
